### PR TITLE
ArgoCD provider: remove ArgoCD/Kubernetes dependency

### PR DESCRIPTION
**Pull request by mcorbin**
The ArgoCD client dependencies are heavy and are a mess to upgrade.

This commit use a simple HTTP client instead of the official ArgoCD client to fetch ArgoCD applications.

All dependencies are also updated.

### CODE REVIEW

**Comment by mcorbin** [comment]
#sre

**Comment by airclovis** [comment]
IIRC the default Argocd client is using GRPC api while here we switch to the rest API. Just to be sure we are aware and it's ok 🙂

**Review by airclovis — APPROVED** [review]
LGTM

**Comment by mcorbin** [comment]
> IIRC the default Argocd client is using GRPC api while here we switch to the rest API. Just to be sure we are aware and it's ok 🙂

yeah it's not an issue. I QA the change locally and everything worked as expected.

**Pull request merged**
